Convert to Prometheus exporter
onedior/nodejs-connector-of-datastream pull request #1
Opened 2020-09-25 09:30 UTC by vnorguet

## Proposed Changes

* Container runs once and then is destroyed
* Add `Dockerfile`
* Add author, version and repository in `package.json`
* Use environment variables instead instead of json configuration file and `.edgerc` file for:
  * Akamai Authentication (aka EdgeGrid)
  * Akamai Datastream id
  * Prometheus url
* Document environment variables in `.env.sample` file
* Drops references to InfluxDB
* Remove useless code and files

## Known issues
* Breaks on 503 errors

2020-09-25 13:35 UTC, alacroix requested changes

2020-09-25 13:35 UTC, alacroix commented on src/index.js
> +        if(prometheusActive && prometheusActive === true){
Attention, depuis ton process.env, t'auras tout le temps des string, donc ton égalité === ne fonctionnera pas

2020-09-25 13:35 UTC, alacroix commented on src/edgegridauth.js
>       * @param {object} edgeGridConfig Edge grid configuration object.
le paramètre n'est plus là du coup

2020-09-28 09:23 UTC, vnorguet commented on src/index.js
> +        if(prometheusActive && prometheusActive === true){
En faite, cette variable ne sert pas dans notre contexte, je l'ai supprimé dans la nouvelle version

2020-09-28 09:23 UTC, vnorguet commented on src/edgegridauth.js
>       * @param {object} edgeGridConfig Edge grid configuration object.
👍

2020-10-05 09:08 UTC, alacroix commented on Dockerfile
> +# RUN npm ci --only=production
on est pas sur une image de prod là du coup ?

2020-10-05 09:08 UTC, alacroix commented on Dockerfile
> +
je rajouterai un `ENV NODE_ENV production` pour optimiser les perfs également

2020-10-05 09:20 UTC, bsemp requested changes
Le Helm chart devrait avoir une option pour déployer un objet `ServiceMonitor` pour informer automatiquement Prometheus que des nouvelles métriques sont accessibles.

2020-10-05 09:20 UTC, bsemp commented on datastream-exporter/values.yaml
> +autoscaling:
Si on enleve la resources hpa, du coup ceci n'est plus nécessaire

2020-10-05 09:20 UTC, bsemp commented on src/index.js
> +app.get('/_ready', (req, res) => {
Je pense que les routes `/_ready` et `/_live` sont inversée dans leur logique:
la readiness probe de Kube sert a dire que le service a fini de démarrer et de s'initiliser
la liveness probe de Kube sert a dire que le service est fonctionnel

Du coup, il faut que le ping de datastream soit présent aussi dans `/_live` car c'est ça qui permet de dire que le service est opérationnel.

Comme je ne vois pas de besoin différencier en les readiness et  liveness probes, on pourrait ne faire qu'une seule route `/health` (pour mieux coller aux standards) :

2020-10-05 09:20 UTC, bsemp commented on datastream-exporter/templates/deployment.yaml
> +          livenessProbe:
Je ferai une route unique `/health` pour la liveness et la readiness probe.
Voir mon commentaire dans le code JS.

2020-10-05 10:29 UTC, vnorguet commented on Dockerfile
> +RUN npm install
Added to .dockerignore

2020-10-05 10:29 UTC, vnorguet commented on Dockerfile
> +RUN npm bin apidoc -i src/ -o doc/
Oui je l'expose sur /doc

2020-10-05 10:32 UTC, vnorguet commented on datastream-exporter/templates/hpa.yaml
> +{{- if .Values.autoscaling.enabled }}
👍

2020-10-05 10:32 UTC, vnorguet commented on Dockerfile
> +
👍

2020-10-05 10:32 UTC, vnorguet commented on Dockerfile
> +# RUN npm ci --only=production
👍

2020-10-05 10:32 UTC, vnorguet commented on datastream-exporter/templates/ingress.yaml
> +{{- if .Values.ingress.enabled -}}
👍

2020-10-05 10:32 UTC, vnorguet commented on Dockerfile
> +# EXPOSE 8080
👍

2020-10-05 10:35 UTC, vnorguet commented on datastream-exporter/values.yaml
> +  repository: nginx
👍

2020-10-05 10:35 UTC, vnorguet commented on datastream-exporter/values.yaml
> +  create: true
👍

2020-10-05 10:35 UTC, vnorguet commented on datastream-exporter/values.yaml
> +autoscaling:
👍

2020-10-05 12:21 UTC, bsemp commented on Dockerfile
> +RUN npm install
Je pensais plus a qqch comme
```
RUN npm install && npm cache clean --force
```

2020-10-05 12:24 UTC, bsemp commented on Dockerfile
> +RUN npm install
Je pensais plus a qqch comme ça pour éviter d'avoir le cache NPM qui fait grossir inutilement l'image docker:

`RUN npm install && npm cache clean --force`

2020-10-05 12:27 UTC, bsemp requested changes

2020-10-05 12:27 UTC, bsemp commented on datastream-exporter/values.yaml
> +  tag: "0.1.0"
non, par par defaut, dans le deployment, le tag de l'image  prend la valeur de `{{ .Values.image.tag | default .Chart.AppVersion }}`, ce parametre sert donc a faire un override et a mon avis c'était très bien comme ça.

2020-10-12 12:41 UTC, merged